### ISSUE TITLE
encapsulate graph request processing

### ISSUE THREAD

**Issue by ismailmo1** [bethschoen/Rotombot#3]
https://github.com/bethryanamey/Rotombot/blob/37a1adfd85d9a81321062ce80f766398cce95538/rotombot_streamlit.py#L131C2-L190C1

encapsulate into function

**Comment by bethschoen** [comment]
A new function has been created for graph request processing: "handle_graph_generation". This has also been done for the data table/summarisation conversation: "handle_data_conversation".
